# Generated by Django 5.2.13 on 2026-04-22 11:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resonans_cms_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=512)),
                ('gemini_use_paid_api', models.BooleanField(default=False)),
                ('gemini_paid_api_key', models.CharField(blank=True, default='', max_length=512)),
                ('text_ai_endpoint_url', models.URLField(blank=True, default='', max_length=2048)),
                ('gemini_model_version', models.CharField(choices=[('gemini-flash-latest', 'gemini-flash-latest'), ('gemini-pro-latest', 'gemini-pro-latest')], default='gemini-flash-latest', max_length=64)),
                ('system_meta_prompt', models.TextField(blank=True, default='')),
                ('gemini_temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('image_ai_api_key', models.CharField(blank=True, default='', max_length=512)),
                ('image_ai_use_paid_api', models.BooleanField(default=False)),
                ('image_ai_paid_api_key', models.CharField(blank=True, default='', max_length=512)),
                ('image_ai_endpoint_url', models.URLField(blank=True, default='', max_length=2048)),
                ('hero_image_model', models.CharField(choices=[('gemini-2.5-flash-image', 'gemini-2.5-flash-image'), ('imagen-4.0-ultra-generate-001', 'imagen-4.0-ultra-generate-001')], default='gemini-2.5-flash-image', max_length=64)),
                ('inline_image_model', models.CharField(choices=[('gemini-2.5-flash-image', 'gemini-2.5-flash-image'), ('imagen-4.0-ultra-generate-001', 'imagen-4.0-ultra-generate-001')], default='imagen-4.0-ultra-generate-001', max_length=64)),
                ('hero_image_system_prompt', models.TextField(blank=True, default='')),
                ('inline_image_system_prompt', models.TextField(blank=True, default='')),
                ('default_aspect_ratio', models.CharField(choices=[('16:9', '16:9'), ('4:3', '4:3'), ('1:1', '1:1')], default='16:9', max_length=8)),
                ('default_primary_color', models.CharField(default='#111827', max_length=7)),
                ('default_secondary_color', models.CharField(default='#2563EB', max_length=7)),
                ('auto_generate_on_save', models.BooleanField(default=False)),
                ('images_upload_path', models.CharField(blank=True, default='', max_length=1024)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI setting',
                'verbose_name_plural': 'AI settings',
                'db_table': 'resonans_cms_core_ai_setting',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (optional).', max_length=2)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('favorite_category', models.ForeignKey(blank=True, help_text='Topic inferred from the page where the user subscribed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscribers', to='resonans_cms_blog.category')),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'verbose_name_plural': 'Newsletter subscribers',
                'db_table': 'resonans_cms_core_newsletter_subscriber',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
