# Generated by Django 5.2.13 on 2026-04-22 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resonans_cms_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='newslettersubscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('unsubscribed_at__isnull', True)), fields=('email',), name='resonans_cms_active_subscriber_email_uniq'),
        ),
    ]
