# Generated by Django 5.2.13 on 2026-04-22 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('hero', 'Hero / Featured'), ('inline', 'Inline')], default='hero', max_length=16)),
                ('prompt', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('aspect_ratio', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resonans_cms_ai_media_generated_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
