# Generated by Django 5.2.13 on 2026-04-22 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resonans_cms_blog', '0002_initial'),
        ('resonans_cms_news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='news_posts', to='resonans_cms_blog.author'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_scope': 'news'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='news_posts', to='resonans_cms_blog.category', verbose_name='Topic'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='news_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resonans_cms_news.newspost'),
        ),
        migrations.AddField(
            model_name='newsposttag',
            name='news_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_post_tags', to='resonans_cms_news.newspost'),
        ),
        migrations.AddField(
            model_name='newsposttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_post_tags', to='resonans_cms_blog.tag'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news_posts', through='resonans_cms_news.NewsPostTag', to='resonans_cms_blog.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='newsposttag',
            unique_together={('news_post', 'tag')},
        ),
    ]
